# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b36d0e4eb9e9d5a10daefccdfa61398ee22e5f260b535798d77f78f9bfe0b01496833e69ef77993f7a6d2b8a0df9dc5f6b46651be0ecaa000ecbd05e55c6cf16

test:
  secret_key_base: fa4741a38745ddb041aff99bfc44b0b6dee1aa17ae730ebe8dcd49bbf075af02d5b3f0fa57a9385c6974a7342de9e2cc51439379f3d6cfa52690cd09b4449cca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
